[package]
name = "nanovg-rs-trial"
version = "0.1.0"
authors = ["cohyou <cohyou@ironoir.io>"]

[dependencies]
glutin = "0.13.0"
gl = "0.10.0"
chrono = "0.4"
lazy_static = "1.0"
rand = "0.4"

[dependencies.nanovg]
version = "0.4.2"
features = ["gl3"]
